esphome:
  name: air-quality-sensor
  name_add_mac_suffix: true
  project:
    name: ferreira_igor.air_quality_sensor
    version: "1.0.0"

esp32:
  # https://www.wemos.cc/en/latest/d32/d32.html
  board: lolin_d32
  framework:
    type: arduino

logger:
  level: DEBUG

wifi:
  ap:

captive_portal:

web_server:
  port: 80
  log: false
  ota: false

ota:

api:
  reboot_timeout: 24h

status_led:
  pin:
    number: 5
    inverted: true

time:
  - platform: sntp
    id: sntp_time

i2c:
  - id: bus_a
    scl: 22
    sda: 21
    scan: true
    frequency: 400kHz
  - id: bus_b
    scl: 32
    sda: 33
    scan: true
    frequency: 400kHz

text_sensor:
  - platform: version
    name: "ESPHome Version"

binary_sensor:
  - platform: status
    name: "Connection Status"

sensor:
  - platform: wifi_signal
    name: "WiFi Signal Strength"

  - platform: uptime
    name: "System Uptime"

  - platform: internal_temperature
    name: "Internal Temperature"

  - platform: adc
    name: "Battery Level"
    pin: 35
    device_class: battery
    unit_of_measurement: "%"
    accuracy_decimals: 0
    entity_category: diagnostic
    attenuation: 11db
    filters:
      - multiply: 2.0
      - calibrate_polynomial:
          degree: 4
          datapoints:
            - 3.00 -> 0.00
            - 3.20 -> 10.00
            - 3.40 -> 20.00
            - 3.56 -> 30.00
            - 3.68 -> 40.00
            - 3.80 -> 50.00
            - 3.88 -> 60.00
            - 3.96 -> 70.00
            - 4.04 -> 80.00
            - 4.12 -> 90.00
            - 4.20 -> 100.00
      - clamp:
          min_value: 0.00
          max_value: 100.00

  - platform: aht10
    i2c_id: bus_a
    temperature:
      name: "Temperature"
      id: sensor_temperature
    humidity:
      name: "Humidity"
      id: sensor_humidity

  - platform: sgp30
    i2c_id: bus_b
    store_baseline: yes
    eco2:
      name: "Equivalent CO2"
      id: sensor_eco2
      filters:
        - exponential_moving_average:
    tvoc:
      name: "Total Volatile Organic Compounds"
      id: sensor_tvoc
      filters:
        - exponential_moving_average:
    compensation:
      temperature_source: sensor_temperature
      humidity_source: sensor_humidity