esphome:
  name: environment-sensor
  name_add_mac_suffix: true
  project:
    name: ferreira_igor.environment_sensor
    version: "1.0.0"

esp32:
  # https://github.com/WeActStudio/WeActStudio.ESP32C3CoreBoard
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

logger:
  level: DEBUG

wifi:
  ap:

captive_portal:

web_server:
  port: 80
  log: false
  ota: false

ota:

api:
  reboot_timeout: 24h

dashboard_import:
  package_import_url: github://ferreira-igor/esphome/blob/main/environment-sensor.yml@main

status_led:
  pin:
    number: 8
    inverted: true

time:
  - platform: sntp
    id: sntp_time

spi:
  clk_pin: 6
  mosi_pin: 7
  miso_pin: 5

spi_device:
  cs_pin: 4

i2c:
  scl: 0
  sda: 1
  scan: true
  frequency: 400kHz

text_sensor:
  - platform: version
    name: "ESPHome Version"

binary_sensor:
  - platform: status
    name: "Connection Status"

  - platform: gpio
    pin:
      number: 9
      mode:
        input: true
        pullup: true
      inverted: true
    id: boot_button

  - platform: gpio
    pin:
      number: 10
      mode:
        input: true
        pullup: false
    device_class: motion
    name: "Motion"
    id: sensor_motion

sensor:
  - platform: wifi_signal
    name: "WiFi Signal Strength"

  - platform: uptime
    name: "System Uptime"

  - platform: internal_temperature
    name: "Internal Temperature"

  - platform: adc
    name: "Battery Level"
    pin: 3
    device_class: battery
    unit_of_measurement: "%"
    accuracy_decimals: 0
    entity_category: diagnostic
    attenuation: 11db
    filters:
      - multiply: 2.0
      - calibrate_polynomial:
          degree: 4
          datapoints:
            - 3.00 -> 0.00
            - 3.20 -> 10.00
            - 3.40 -> 20.00
            - 3.56 -> 30.00
            - 3.68 -> 40.00
            - 3.80 -> 50.00
            - 3.88 -> 60.00
            - 3.96 -> 70.00
            - 4.04 -> 80.00
            - 4.12 -> 90.00
            - 4.20 -> 100.00
      - clamp:
          min_value: 0.00
          max_value: 100.00

  - platform: bme280
    address: 0x77
    temperature:
      name: "Temperature"
      id: sensor_temperature
    humidity:
      name: "Humidity"
      id: sensor_humidity
    pressure:
      name: "Pressure"
      id: sensor_pressure

  - platform: sgp4x
    voc:
      name: "Volatile Organic Compound Index"
      id: sensor_voc
    compensation:
      temperature_source: sensor_temperature
      humidity_source: sensor_humidity
